export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'violet', top: '20px', padding: '2rem' }}>
          <p>Header</p> 
        </header>
        {children}
        <footer style={{ backgroundColor: 'navajowhite', top: '30px', padding: '2rem' }}><p>Footer</p></footer>
        </body>
    </html>
  )
}
